### ISSUE TITLE
Formalize metadata that model will use

### ISSUE THREAD

**Issue by JayDosunmu** [Rosenblatt-LLC/kolmogorov#18]
Besides the satellite class, there is other metadata that we can make use of. We need to determine what is necessary.

Orientation? Atmospheric distortion settings? Etc.

**Comment by rjwalden** [comment]
draw.io graph covers this

**Comment by rjwalden** [comment]
@JayDosunmu let's definitely bring this up to daniel tomorrow

**Comment by JayDosunmu** [comment]
@rjwalden good deal
