### ISSUE TITLE
Fix the Observatory within Unity

### ISSUE THREAD

**Issue by rjwalden** [Rosenblatt-LLC/kolmogorov#3]
The observatory must remain in the same orientation and position during all photos.

**Comment by rjwalden** [comment]
@JayDosunmu was this fixed with the last PR?

**Comment by JayDosunmu** [comment]
@rjwalden It wasn't, but this is likely no longer necessary, as the orientation is currently calculated in a consistent way

**Comment by rjwalden** [comment]
I agree, let's run this by daniel tomorrow as well just to be safe

**Comment by JayDosunmu** [comment]
Closing, because a better solution was found
